CREATE PROCEDURE STAFF_ADD
@PIB NVARCHAR(100) = NULL,
@BIRTHDATE DATE = NULL,
@POSITIONID INT = NULL,
@SALARY FLOAT = NULL,
@ISFIRED BIT = 0
AS
BEGIN
BEGIN TRAN
	BEGIN TRY
		INSERT INTO STAFF
		(PIB,
		BIRTHDATE,
		POSITIONID,
		SALARY,
		ISFIRED)
		VALUES
		(@PIB,
		@BIRTHDATE,
		@POSITIONID,
		@SALARY,
		@ISFIRED)
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RAISERROR('Помилка при додаванні користувача. Відкат транзакції.', 16, 1)
	END CATCH
END