CREATE PROCEDURE STAFF_EDIT
@PIB NVARCHAR(100) = NULL,
@BIRTHDATE DATE = NULL,
@POSITIONID INT = NULL,
@SALARY FLOAT = NULL,
@STAFFID INT = NULL
AS
BEGIN
BEGIN TRAN
	BEGIN TRY
		UPDATE STAFF
		SET PIB = @PIB,
		BIRTHDATE = @BIRTHDATE,
		POSITIONID = @POSITIONID,
		SALARY = @SALARY
		WHERE ID = @STAFFID

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RAISERROR('Помилка при редагуванні даних користувача. Відкат транзакції.', 16, 1)
	END CATCH
END