CREATE PROCEDURE STAFF_STATISTICS
AS
BEGIN
	SELECT CAST(COUNT(*) AS NVARCHAR(100)) FROM STAFF
	WHERE ISFIRED = 0
	UNION ALL
	SELECT CAST(ROUND(AVG(SALARY), 2) AS NVARCHAR(100)) FROM STAFF
	WHERE ISFIRED = 0
END;
